version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 269174114725.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - docker build -t simpledockerservice .
      - docker tag simpledockerservice:latest 269174114725.dkr.ecr.us-east-1.amazonaws.com/simpledockerservice:latest

  post_build:
    commands:
      - docker push 269174114725.dkr.ecr.us-east-1.amazonaws.com/simpledockerservice:latest
